// <auto-generated />
using System;
using EducationalGame.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EducationalGame.Migrations
{
    [DbContext(typeof(EducationalGameContext))]
    partial class EducationalGameContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EducationalGame.Model.GameQuiz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<int?>("QuizCategoryId");

                    b.HasKey("Id");

                    b.HasIndex("QuizCategoryId");

                    b.ToTable("GameQuizes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Answer = "СЛЪНЦЕ",
                            Question = "Най-близката до нас звезда, която ни осигурява светлина и топлина",
                            QuizCategoryId = 1
                        },
                        new
                        {
                            Id = 2,
                            Answer = "МАРС",
                            Question = "Една от планетите в Слънчевата система.",
                            QuizCategoryId = 1
                        },
                        new
                        {
                            Id = 3,
                            Answer = "ЛУНА",
                            Question = "Кой е единственият естествен спътник на Земята ?",
                            QuizCategoryId = 1
                        },
                        new
                        {
                            Id = 4,
                            Answer = "ЗЕМЯ",
                            Question = "Планета от Слънчевата система, която предоставя условия за живот на всички живи същества.",
                            QuizCategoryId = 1
                        },
                        new
                        {
                            Id = 5,
                            Answer = "ЮРИЙ ГАГАРИН",
                            Question = "Името на първия човек, направил обиколка около Земята с космически кораб. /1961 г./",
                            QuizCategoryId = 1
                        },
                        new
                        {
                            Id = 6,
                            Answer = "ГЕОРГИ ИВАНОВ",
                            Question = "Името на първия български космонавт.",
                            QuizCategoryId = 1
                        },
                        new
                        {
                            Id = 7,
                            Answer = "ЗВЕЗДИ",
                            Question = "Естествени небесни тела, които светят със собствена светлина.",
                            QuizCategoryId = 1
                        },
                        new
                        {
                            Id = 8,
                            Answer = "ПЛАНЕТИ",
                            Question = "Тела, които светят с отразена слънчева светлина.",
                            QuizCategoryId = 1
                        },
                        new
                        {
                            Id = 9,
                            Answer = "ТОН",
                            Question = "Единица за маса на телата, равна на 1000 кг.",
                            QuizCategoryId = 1
                        },
                        new
                        {
                            Id = 10,
                            Answer = "ВОДА",
                            Question = "Вещество в природата, което /в твърдо състояние/ се топи при 0 градуса по Целзий, а на морското равнище кипи при 100 градуса по Целзий.",
                            QuizCategoryId = 1
                        },
                        new
                        {
                            Id = 11,
                            Answer = "ФОРМА",
                            Question = "Три са основните характеристики на телата. Една от тях. Коя е тя? Опитайте се да познаете! ",
                            QuizCategoryId = 1
                        },
                        new
                        {
                            Id = 12,
                            Answer = "ЦВЯТ",
                            Question = "Едно от по-важните свойства на веществата. Кое е то?",
                            QuizCategoryId = 1
                        },
                        new
                        {
                            Id = 13,
                            Answer = "СМЕС",
                            Question = "Какво представлява въздухът?",
                            QuizCategoryId = 1
                        },
                        new
                        {
                            Id = 14,
                            Answer = "ВИТАМИНИ",
                            Question = "Едно от основните вещества, които съставят нашата храна. Има го в плодовете и зеленчуците.",
                            QuizCategoryId = 1
                        },
                        new
                        {
                            Id = 15,
                            Answer = "НИКОТИН",
                            Question = "Вещество, вредно за  здравето на човека и застрашаващо неговия организъм.",
                            QuizCategoryId = 1
                        },
                        new
                        {
                            Id = 16,
                            Answer = "КЛЕТКА",
                            Question = "Основната градивна единица на всички организми",
                            QuizCategoryId = 1
                        },
                        new
                        {
                            Id = 17,
                            Answer = "ЛУПА",
                            Question = "Най-просто устроеният увеличителен уред, който увеличава образа на обектите от 2 до 30 пъти.",
                            QuizCategoryId = 1
                        },
                        new
                        {
                            Id = 18,
                            Answer = "БАКТЕРИИ",
                            Question = "Едноклетъчни организми с много малки размери, полезни и вредни за човека.",
                            QuizCategoryId = 1
                        },
                        new
                        {
                            Id = 19,
                            Answer = "АМЕБА",
                            Question = "Едноклетъчно животно.",
                            QuizCategoryId = 1
                        },
                        new
                        {
                            Id = 20,
                            Answer = "КОН",
                            Question = "Растителноядно /тревопасно/ животно.",
                            QuizCategoryId = 1
                        },
                        new
                        {
                            Id = 21,
                            Answer = "ЛИСИЦА",
                            Question = "Месояден бозайник.",
                            QuizCategoryId = 1
                        },
                        new
                        {
                            Id = 22,
                            Answer = "КОМАР",
                            Question = "Кръвосмучещо насекомо.",
                            QuizCategoryId = 1
                        },
                        new
                        {
                            Id = 23,
                            Answer = "ПРАСЕ",
                            Question = "Всеядно животно.",
                            QuizCategoryId = 1
                        },
                        new
                        {
                            Id = 24,
                            Answer = "КИТ",
                            Question = "Воден бозайник.",
                            QuizCategoryId = 1
                        },
                        new
                        {
                            Id = 25,
                            Answer = "ПРИЛЕП",
                            Question = "Летящ бозайник.",
                            QuizCategoryId = 1
                        },
                        new
                        {
                            Id = 26,
                            Answer = "КОРЕН",
                            Question = "Орган, с който растението всмуква от почвата вода и минерални вещества.",
                            QuizCategoryId = 1
                        },
                        new
                        {
                            Id = 27,
                            Answer = "МЕД",
                            Question = "Хранителен продукт, богат на въглехидрати.",
                            QuizCategoryId = 1
                        },
                        new
                        {
                            Id = 28,
                            Answer = "СТОМАХ",
                            Question = "Орган на храносмилателната система.",
                            QuizCategoryId = 1
                        },
                        new
                        {
                            Id = 29,
                            Answer = "ВИРУС",
                            Question = "Причинител на дихателни заболявания.",
                            QuizCategoryId = 1
                        },
                        new
                        {
                            Id = 30,
                            Answer = "БЪБРЕК",
                            Question = "Основен орган на отделителната система.",
                            QuizCategoryId = 1
                        },
                        new
                        {
                            Id = 31,
                            Answer = "МЕСО",
                            Question = "Хранителен продукт, богат на белтъчини",
                            QuizCategoryId = 1
                        },
                        new
                        {
                            Id = 32,
                            Answer = "НОС",
                            Question = "Орган от дихателната система на човека",
                            QuizCategoryId = 1
                        },
                        new
                        {
                            Id = 33,
                            Answer = "ГРИП",
                            Question = "Основна болест на дихателната система",
                            QuizCategoryId = 1
                        },
                        new
                        {
                            Id = 34,
                            Answer = "ХЕПАТИТ",
                            Question = "Основна болест на храносмилателната система ",
                            QuizCategoryId = 1
                        },
                        new
                        {
                            Id = 35,
                            Answer = "КРАВА",
                            Question = "Тревопасно животно",
                            QuizCategoryId = 1
                        },
                        new
                        {
                            Id = 36,
                            Answer = "ВЪЛК",
                            Question = "Месояден бозайник",
                            QuizCategoryId = 1
                        },
                        new
                        {
                            Id = 37,
                            Answer = "ДЕЛФИН",
                            Question = "Воден бозайник",
                            QuizCategoryId = 1
                        },
                        new
                        {
                            Id = 38,
                            Answer = "РИБИ",
                            Question = "Група животни, които живеят във водата и дишат с хриле",
                            QuizCategoryId = 1
                        },
                        new
                        {
                            Id = 39,
                            Answer = "ЧАКАЛ",
                            Question = "Представител на род \"кучета\"",
                            QuizCategoryId = 1
                        },
                        new
                        {
                            Id = 40,
                            Answer = "ЛЪВ",
                            Question = "Представител на род \"котки\"",
                            QuizCategoryId = 1
                        },
                        new
                        {
                            Id = 41,
                            Answer = "АСТЕРОИДИ",
                            Question = "Небесни тела с малка маса, малки размери и обикновено неправилна форма. Намират се между орбитите на Марс и Юпитер.",
                            QuizCategoryId = 1
                        },
                        new
                        {
                            Id = 42,
                            Answer = "КОМЕТИ",
                            Question = "Светли петна, от които излиза опашка, когато минават близо до Слънцето  -  \"опашати звезди\"",
                            QuizCategoryId = 1
                        },
                        new
                        {
                            Id = 43,
                            Answer = "МЕТЕОРИ",
                            Question = "Малки твърди части от комети или от други небесни тела, които навлизат в земната атмосфера и изгарят  -  \"падащи звезди\"",
                            QuizCategoryId = 1
                        },
                        new
                        {
                            Id = 44,
                            Answer = "КАФЯВ",
                            Question = "С какъв цвят се означават планините на географската карта?",
                            QuizCategoryId = 2
                        },
                        new
                        {
                            Id = 45,
                            Answer = "СОФИЯ  ",
                            Question = "Коя е столицата на България?",
                            QuizCategoryId = 2
                        },
                        new
                        {
                            Id = 46,
                            Answer = "МАРИЦА",
                            Question = "Река в България, минаваща през град Пловдив.",
                            QuizCategoryId = 2
                        },
                        new
                        {
                            Id = 47,
                            Answer = "МУСАЛА",
                            Question = "Кой е най-високият връх в България?",
                            QuizCategoryId = 2
                        },
                        new
                        {
                            Id = 48,
                            Answer = "ВАРНА",
                            Question = "Голям български град, наричан \"морската столица на България\".",
                            QuizCategoryId = 2
                        },
                        new
                        {
                            Id = 49,
                            Answer = "ГЪРЦИЯ",
                            Question = "Европейска държава, с която България граничи на юг.",
                            QuizCategoryId = 2
                        },
                        new
                        {
                            Id = 50,
                            Answer = "РИЛА",
                            Question = "Най-високата планина в България.",
                            QuizCategoryId = 2
                        },
                        new
                        {
                            Id = 51,
                            Answer = "КАРЛОВО",
                            Question = "Град в България - родно място на Васил Левски.",
                            QuizCategoryId = 2
                        },
                        new
                        {
                            Id = 52,
                            Answer = "СОПОТ",
                            Question = "Родното място на Иван Вазов",
                            QuizCategoryId = 2
                        },
                        new
                        {
                            Id = 53,
                            Answer = "СТАРА ПЛАНИНА",
                            Question = "Най-дългата планина в България.",
                            QuizCategoryId = 2
                        },
                        new
                        {
                            Id = 54,
                            Answer = "ОКОТО",
                            Question = "Името на едно от рилските езера.",
                            QuizCategoryId = 2
                        },
                        new
                        {
                            Id = 55,
                            Answer = "ЕВРОПА",
                            Question = "На кой континент се намира България?",
                            QuizCategoryId = 2
                        },
                        new
                        {
                            Id = 56,
                            Answer = "ДУНАВ",
                            Question = "Гранична българска река.",
                            QuizCategoryId = 2
                        },
                        new
                        {
                            Id = 57,
                            Answer = "РУСЕ",
                            Question = "Голям крайдунавски град.",
                            QuizCategoryId = 2
                        },
                        new
                        {
                            Id = 58,
                            Answer = "ВЕЛИКО ТЪРНОВО",
                            Question = "Град - столица на Второто Българско царство.",
                            QuizCategoryId = 2
                        },
                        new
                        {
                            Id = 59,
                            Answer = "ЗЕЛЕН",
                            Question = "С какъв цвят се означават равнините на географската карта?",
                            QuizCategoryId = 2
                        },
                        new
                        {
                            Id = 60,
                            Answer = "СЕВЕР",
                            Question = "Каква посока показва горната част на географската карта?",
                            QuizCategoryId = 2
                        },
                        new
                        {
                            Id = 61,
                            Answer = "РОДОПИ",
                            Question = "Коя е най-обширната българска планина?",
                            QuizCategoryId = 2
                        },
                        new
                        {
                            Id = 62,
                            Answer = "ИСКЪР",
                            Question = "Коя е най-дългата българска река?",
                            QuizCategoryId = 2
                        },
                        new
                        {
                            Id = 63,
                            Answer = "ОСТРОВ",
                            Question = "Коя земна форма отговаря на описанието - \"суша, заобиколена от всички страни с вода\"?",
                            QuizCategoryId = 2
                        },
                        new
                        {
                            Id = 64,
                            Answer = "ЧЕРНО МОРЕ",
                            Question = "Източната граница на България",
                            QuizCategoryId = 2
                        },
                        new
                        {
                            Id = 65,
                            Answer = "СИН",
                            Question = "С какъв цвят се изобразяват на географската карта реките, езерата, моретата?",
                            QuizCategoryId = 2
                        },
                        new
                        {
                            Id = 66,
                            Answer = "ТУРЦИЯ",
                            Question = "С коя държава граничим на югоизток?",
                            QuizCategoryId = 2
                        },
                        new
                        {
                            Id = 67,
                            Answer = "БОТЕВ",
                            Question = "Най-високият връх в Стара планина",
                            QuizCategoryId = 2
                        },
                        new
                        {
                            Id = 68,
                            Answer = "СЪРБИЯ",
                            Question = "Държава на Балканския полуостров, с която граничим на запад",
                            QuizCategoryId = 2
                        },
                        new
                        {
                            Id = 69,
                            Answer = "ВИХРЕН",
                            Question = "Най-високият връх в Пирин планина",
                            QuizCategoryId = 2
                        },
                        new
                        {
                            Id = 70,
                            Answer = "БАТАК",
                            Question = "Град в България, където по време на Априлското въстание през 1876 година са избити много българи",
                            QuizCategoryId = 2
                        },
                        new
                        {
                            Id = 71,
                            Answer = "НОС",
                            Question = "Коя земна форма отговаря на описанието - \"остро вдадена в морето суша\"?",
                            QuizCategoryId = 2
                        },
                        new
                        {
                            Id = 72,
                            Answer = "ПЛАЖОВЕТЕ",
                            Question = "Най-голямото природно богатство на Черноморското крайбрежие",
                            QuizCategoryId = 2
                        },
                        new
                        {
                            Id = 73,
                            Answer = "ВИТОША ",
                            Question = "Планина, която е близо до нашата столица  град София",
                            QuizCategoryId = 2
                        },
                        new
                        {
                            Id = 74,
                            Answer = "СРЕБЪРНА",
                            Question = "Резерват за редки птици, недалече от град Силистра",
                            QuizCategoryId = 2
                        },
                        new
                        {
                            Id = 75,
                            Answer = "КОЗЛОДУЙ",
                            Question = "Край кой български град се намира най-голямата електроцентрала у нас ?",
                            QuizCategoryId = 2
                        },
                        new
                        {
                            Id = 76,
                            Answer = "ОСЪМ",
                            Question = "Река, която извира от Стара планина. На нея е разположен град Ловеч. Кое е нейното име ?",
                            QuizCategoryId = 2
                        },
                        new
                        {
                            Id = 77,
                            Answer = "ЛОВЕЧ",
                            Question = "Град, който е разположен на река Осъм. Наричат го  \"града на люляците\".",
                            QuizCategoryId = 2
                        },
                        new
                        {
                            Id = 78,
                            Answer = "ГАБРОВО",
                            Question = "Град, разположен по течението на река Янтра. Тук е открита първата гимназия в България - \"Априловската\". Край града се намира музеят на открито - Етъра\"",
                            QuizCategoryId = 2
                        },
                        new
                        {
                            Id = 79,
                            Answer = "СЛИВЕН",
                            Question = "Град, в който е открита първата българска фабрика за производство на платове още през 1834 година",
                            QuizCategoryId = 2
                        },
                        new
                        {
                            Id = 80,
                            Answer = "КАЗАНЛЪК",
                            Question = "Български град - \"градът на розите\"",
                            QuizCategoryId = 2
                        },
                        new
                        {
                            Id = 81,
                            Answer = "ПЛОВДИВ",
                            Question = "Вторият по големина град в България",
                            QuizCategoryId = 2
                        },
                        new
                        {
                            Id = 82,
                            Answer = "ЯМБОЛ",
                            Question = "Град разположен на река Тунджа",
                            QuizCategoryId = 2
                        },
                        new
                        {
                            Id = 83,
                            Answer = "БОРОВЕЦ",
                            Question = "Известен български курорт близо до град Самоков",
                            QuizCategoryId = 2
                        },
                        new
                        {
                            Id = 84,
                            Answer = "ПАМПОРОВО",
                            Question = "Зимен курорт близо до град Смолян",
                            QuizCategoryId = 2
                        },
                        new
                        {
                            Id = 85,
                            Answer = "АРДА",
                            Question = "По бреговете на коя река е разположен град Кърджали",
                            QuizCategoryId = 2
                        },
                        new
                        {
                            Id = 86,
                            Answer = "АЛБЕНА",
                            Question = "Красив курорт по българското черноморско крайбрежие, на север от град Варна",
                            QuizCategoryId = 2
                        },
                        new
                        {
                            Id = 87,
                            Answer = "ГЛАРУС",
                            Question = "Птица, която обикновено можем да видим на българското Черноморие",
                            QuizCategoryId = 2
                        },
                        new
                        {
                            Id = 88,
                            Answer = "ЕЗЕРО",
                            Question = "Вдлъбнатина в земна повърхност, запълнена с вода",
                            QuizCategoryId = 2
                        },
                        new
                        {
                            Id = 89,
                            Answer = "ЯЗОВИР",
                            Question = "Изкуствено езеро, създадено от хората, когато реката се прегради със стена",
                            QuizCategoryId = 2
                        },
                        new
                        {
                            Id = 90,
                            Answer = "МОРЕ",
                            Question = "Голямо количество солена вода, обградена изцяло или само отчасти със земя",
                            QuizCategoryId = 2
                        },
                        new
                        {
                            Id = 91,
                            Answer = "БАНСКО",
                            Question = "Известен зимен курорт в планината Пирин ",
                            QuizCategoryId = 2
                        },
                        new
                        {
                            Id = 92,
                            Answer = "НИЗИНА",
                            Question = "Много ниска и равна земна форма край река или море",
                            QuizCategoryId = 2
                        },
                        new
                        {
                            Id = 93,
                            Answer = "ДОБРУДЖА",
                            Question = "Там се ражда повечето жито за хляба на нашата трапеза. Наричат я \"житницата\" на България",
                            QuizCategoryId = 2
                        },
                        new
                        {
                            Id = 94,
                            Answer = "ИЗТОК",
                            Question = "Като се обърнеш с лице към географската карта коя посока на света сочи дясната ти ръка ?",
                            QuizCategoryId = 2
                        },
                        new
                        {
                            Id = 95,
                            Answer = "ЗАПАД",
                            Question = "Една от посоките на света. Като сме с лице и разперени ръце към географската карта лявата ни ръка я показва ",
                            QuizCategoryId = 2
                        },
                        new
                        {
                            Id = 96,
                            Answer = "КРУМ",
                            Question = "От кой хан са били създадени първите писани закони в България?",
                            QuizCategoryId = 3
                        },
                        new
                        {
                            Id = 97,
                            Answer = "ОМУРТАГ",
                            Question = "При кой хан се извършила голяма строителна дейност и била възстановена разрушената столица?",
                            QuizCategoryId = 3
                        },
                        new
                        {
                            Id = 98,
                            Answer = "БОРИС",
                            Question = "При кой български владетел става покръстването на българите, приемането на християнската вяра?",
                            QuizCategoryId = 3
                        },
                        new
                        {
                            Id = 99,
                            Answer = "ПРЕСЛАВ",
                            Question = "Кой град е бил столица на България по време на покръстването?",
                            QuizCategoryId = 3
                        },
                        new
                        {
                            Id = 100,
                            Answer = "САМУИЛ",
                            Question = "Войниците на кой български цар били пленени и ослепени от византийския император Василий Втори?",
                            QuizCategoryId = 3
                        },
                        new
                        {
                            Id = 101,
                            Answer = "ДЖАМИЯ",
                            Question = "Как се нарича молитвеният дом на мюсюлманите?",
                            QuizCategoryId = 3
                        },
                        new
                        {
                            Id = 102,
                            Answer = "МЮСЮЛМАНИ",
                            Question = "Вярващи, които изповядват исляма",
                            QuizCategoryId = 3
                        },
                        new
                        {
                            Id = 103,
                            Answer = "КОРАН",
                            Question = "Свещената книга на мюсюлманите",
                            QuizCategoryId = 3
                        },
                        new
                        {
                            Id = 104,
                            Answer = "ТАНГРА",
                            Question = "Кой бог почитали прабългарите?",
                            QuizCategoryId = 3
                        },
                        new
                        {
                            Id = 105,
                            Answer = "СИМЕОН",
                            Question = "Управлението на кой български цар се определя като \"Златен век на българската култура\" ?",
                            QuizCategoryId = 3
                        },
                        new
                        {
                            Id = 106,
                            Answer = "КАЛОЯН",
                            Question = "Кой български владетел през 1205 година победил латинците /кръстоносците/ при Одрин и пленил техния император Балдуин?",
                            QuizCategoryId = 3
                        },
                        new
                        {
                            Id = 107,
                            Answer = "ИВАН АСЕН ВТОРИ",
                            Question = "Кой български цар през 1230 година победил при село Клокотница епирския владетел Теодор Комнин?",
                            QuizCategoryId = 3
                        },
                        new
                        {
                            Id = 108,
                            Answer = "ДЕСПОТ",
                            Question = "Първи помощник на царя",
                            QuizCategoryId = 3
                        },
                        new
                        {
                            Id = 109,
                            Answer = "ТЪРНОВО",
                            Question = "Коя била столицата на Втората Българска държава?",
                            QuizCategoryId = 3
                        },
                        new
                        {
                            Id = 110,
                            Answer = "СУЛТАН",
                            Question = "В края на 14 век, през 1396 година, средновековна България попаднала под османска власт. Как се наричал този, който стоял начело на Османската империя?",
                            QuizCategoryId = 3
                        },
                        new
                        {
                            Id = 111,
                            Answer = "ИСЛЯМ",
                            Question = "Каква религия изповядвали османците?",
                            QuizCategoryId = 3
                        },
                        new
                        {
                            Id = 112,
                            Answer = "АСПАРУХ",
                            Question = "От кой владетел, през 681 година, била създадена българската държава?",
                            QuizCategoryId = 3
                        },
                        new
                        {
                            Id = 113,
                            Answer = "АСЕН И ПЕТЪР",
                            Question = "С въстанието на кои двама братя било възобновено Българското царство през 1185 година?",
                            QuizCategoryId = 3
                        },
                        new
                        {
                            Id = 114,
                            Answer = "ПЕРУН",
                            Question = "Кой бог почитали славяните, преди да приемат християнството?",
                            QuizCategoryId = 3
                        },
                        new
                        {
                            Id = 115,
                            Answer = "ОХРИД",
                            Question = "Кой град бил столица на България при царуването на Самуил?",
                            QuizCategoryId = 3
                        },
                        new
                        {
                            Id = 116,
                            Answer = "БИБЛИЯ",
                            Question = "Свещената книга на християните",
                            QuizCategoryId = 3
                        },
                        new
                        {
                            Id = 117,
                            Answer = "КАДИЯ",
                            Question = "Мюсюлмански съдия",
                            QuizCategoryId = 3
                        },
                        new
                        {
                            Id = 118,
                            Answer = "ХАЛИФ",
                            Question = "Титла на политическия и религиозен водач на мюсюлманската общност",
                            QuizCategoryId = 3
                        },
                        new
                        {
                            Id = 119,
                            Answer = "РИЦАР",
                            Question = "Тежковъоръжен конник с благородно потекло в Западна Европа, за когото войната била професия",
                            QuizCategoryId = 3
                        },
                        new
                        {
                            Id = 120,
                            Answer = "КЕСАР",
                            Question = "Най-високата титла във Византия след тази на императора. Хан Тервел бил единствения чужд владетел, който я получил. Той се прославил като спасител на  Европа от арабското нашествие.",
                            QuizCategoryId = 3
                        },
                        new
                        {
                            Id = 121,
                            Answer = "ВИКИНГИ",
                            Question = "Племена, които населявали Скандинавския полуостров, предци на днешните датчани, норвежци, шведи и исландци",
                            QuizCategoryId = 3
                        },
                        new
                        {
                            Id = 122,
                            Answer = "ЦАР",
                            Question = "Титла на славянски владетел, равна на императорската",
                            QuizCategoryId = 3
                        },
                        new
                        {
                            Id = 123,
                            Answer = "СИНОД",
                            Question = "Ръководен орган на Християнските църкви в европейския Изток",
                            QuizCategoryId = 3
                        },
                        new
                        {
                            Id = 124,
                            Answer = "КАТОЛИК",
                            Question = "Християнин от Западна Европа",
                            QuizCategoryId = 3
                        },
                        new
                        {
                            Id = 125,
                            Answer = "КАТЕДРАЛА",
                            Question = "Главна градска църква",
                            QuizCategoryId = 3
                        },
                        new
                        {
                            Id = 126,
                            Answer = "СВЕТА ИНКВИЗИЦИЯ",
                            Question = "Съдебна институция на Католическата църква за борба срущу еретиците",
                            QuizCategoryId = 3
                        },
                        new
                        {
                            Id = 127,
                            Answer = "КРЪСТОНОСЦИ",
                            Question = "Участници в кръстоносните походи, получили името си от кръста, който поставили върху наметалата си",
                            QuizCategoryId = 3
                        },
                        new
                        {
                            Id = 128,
                            Answer = "АНГЛИЯ",
                            Question = "Една от държавите, участници в Стогодишната война, продължила от 1337 година до 1453 година",
                            QuizCategoryId = 3
                        },
                        new
                        {
                            Id = 129,
                            Answer = "ДЕСПОТ",
                            Question = "Титла на самостоятелен владетел",
                            QuizCategoryId = 3
                        },
                        new
                        {
                            Id = 130,
                            Answer = "ВЕЗИР",
                            Question = "Висш държавен служител - министър в Османската империя",
                            QuizCategoryId = 3
                        },
                        new
                        {
                            Id = 131,
                            Answer = "ЕНИЧАРИ",
                            Question = "Войници от османската пехота, набирани от християнското население чрез т.нар. кръвен данък /девширме/ и преминали през специално обучение",
                            QuizCategoryId = 3
                        },
                        new
                        {
                            Id = 132,
                            Answer = "СРЕДНОВЕКОВИЕ",
                            Question = "Историческа епоха, която обхваща времето от 5 век до 15 век",
                            QuizCategoryId = 3
                        },
                        new
                        {
                            Id = 133,
                            Answer = "ЦЪРКВА",
                            Question = "Православен християнски храм",
                            QuizCategoryId = 3
                        },
                        new
                        {
                            Id = 134,
                            Answer = "УНИВЕРСИТЕТ",
                            Question = "Висше училище, общност от преподаватели и студенти, която се самоуправлява",
                            QuizCategoryId = 3
                        },
                        new
                        {
                            Id = 135,
                            Answer = "ЕРЕС",
                            Question = "Учение, което се отклонява от общоприетите принципи на Християнската църква",
                            QuizCategoryId = 3
                        },
                        new
                        {
                            Id = 136,
                            Answer = "ПАТРИАРХ",
                            Question = "Духовен глава на православната християнска църква",
                            QuizCategoryId = 3
                        },
                        new
                        {
                            Id = 137,
                            Answer = "ПАПА",
                            Question = "Духовен глава на християните в Западна Европа",
                            QuizCategoryId = 3
                        },
                        new
                        {
                            Id = 138,
                            Answer = "КРАЛ",
                            Question = "Титла на владетел в Западна Европа",
                            QuizCategoryId = 3
                        },
                        new
                        {
                            Id = 139,
                            Answer = "МАНАСТИР",
                            Question = "Религиозна общност от монаси или монахини, която има свой устав и се ръководи от игумен или игуменка   /в Западна Европа  -абат или абатиса /",
                            QuizCategoryId = 3
                        },
                        new
                        {
                            Id = 140,
                            Answer = "ВАРВАРИ",
                            Question = "Как наричали римляните всички останали народи, чийто език не разбирали и които не принадлежали на тяхната култура",
                            QuizCategoryId = 3
                        },
                        new
                        {
                            Id = 141,
                            Answer = "ХАН",
                            Question = "Титла на племенен вожд или на самостоятелен владетел при древните българи",
                            QuizCategoryId = 3
                        },
                        new
                        {
                            Id = 142,
                            Answer = "КНЯЗ",
                            Question = "Титла на племенен вожд или на самостоятелен владетел при славяните",
                            QuizCategoryId = 3
                        },
                        new
                        {
                            Id = 143,
                            Answer = "ВАСИЛЕВС",
                            Question = "Титла на византийския император",
                            QuizCategoryId = 3
                        },
                        new
                        {
                            Id = 144,
                            Answer = "РАЯ",
                            Question = "Всички поданици на султана независимо от своята вяра и произход, които плащат данъци",
                            QuizCategoryId = 3
                        },
                        new
                        {
                            Id = 145,
                            Answer = "ДЕСЯТЪК",
                            Question = "Годишен данък в размер на една десета част от всички добиви, който всяко селско семейство изплащало на спахията",
                            QuizCategoryId = 3
                        },
                        new
                        {
                            Id = 146,
                            Answer = "СПАХИЯ",
                            Question = "Войник от османската конница, на който султанът давал земя, от чиито приходи се издържал, докато му служи ",
                            QuizCategoryId = 3
                        },
                        new
                        {
                            Id = 147,
                            Answer = "ЧАРШИЯ",
                            Question = "Стопанският център на градовете, търговска улица",
                            QuizCategoryId = 3
                        },
                        new
                        {
                            Id = 148,
                            Answer = "ЕСНАФ",
                            Question = "Професионална организация на занаятчиите от една професия, която защитавала интересите на своите членове",
                            QuizCategoryId = 3
                        },
                        new
                        {
                            Id = 149,
                            Answer = "ХАЙДУТИН",
                            Question = "Отмъстител и народен закрилник за българите по време на османската власт",
                            QuizCategoryId = 3
                        },
                        new
                        {
                            Id = 150,
                            Answer = "ИКОНА",
                            Question = "Изображение на Бог, Света Богородица, светци или библейски сцени, изписвано върху гладка дървена основа",
                            QuizCategoryId = 3
                        },
                        new
                        {
                            Id = 151,
                            Answer = "ГЕОРГИ РАКОВСКИ",
                            Question = "Името на български революционер, признат за родоначалник на организираната борба за свобода",
                            QuizCategoryId = 3
                        },
                        new
                        {
                            Id = 152,
                            Answer = "ЧЕТА",
                            Question = "Група от въоръжени хора, участници в освободителните борби",
                            QuizCategoryId = 3
                        },
                        new
                        {
                            Id = 153,
                            Answer = "ЛЕГИЯ",
                            Question = "Доброволчески отряд преди Освобождението, създаден в Белград, българска войска",
                            QuizCategoryId = 3
                        },
                        new
                        {
                            Id = 154,
                            Answer = "БУКУРЕЩ",
                            Question = "В кой румънски град през 1869 година бил създаден Българският революционен централен комитет?",
                            QuizCategoryId = 3
                        },
                        new
                        {
                            Id = 155,
                            Answer = "ЛЮБЕН КАРАВЕЛОВ",
                            Question = "Кой застанал начело на Българския ревеволюционен централен комитет, създаден  през 1869 година в Букурещ?",
                            QuizCategoryId = 3
                        },
                        new
                        {
                            Id = 156,
                            Answer = "ВАСИЛ ЛЕВСКИ",
                            Question = "Кой обикалял страната и създавал революционни комитети за подготовка на въстание?",
                            QuizCategoryId = 3
                        },
                        new
                        {
                            Id = 157,
                            Answer = "ХРИСТО БОТЕВ",
                            Question = "Български поет-революционер, загинал за свободата на България на 2 юни 1876 година",
                            QuizCategoryId = 3
                        },
                        new
                        {
                            Id = 158,
                            Answer = "ПАНАЙОТ ВОЛОВ",
                            Question = "Името на главния апостол в Панагюрище",
                            QuizCategoryId = 3
                        },
                        new
                        {
                            Id = 159,
                            Answer = "ГЕОРГИ БЕНКОВСКИ",
                            Question = "Кой бил водач на \"Хвърковатата чета\" по време на Априлското въстание?",
                            QuizCategoryId = 3
                        },
                        new
                        {
                            Id = 160,
                            Answer = "РАЙНА ПОПГЕОРГИЕВА",
                            Question = "Кой ушил и извезал  знамето на панагюрци по време на Априлското въстание през 1876 година?",
                            QuizCategoryId = 3
                        },
                        new
                        {
                            Id = 161,
                            Answer = "ТРЕТИ МАРТ",
                            Question = "Националният празник на страната ни е свързан с Освобождението на България от османска власт през 1878 година.Коя е датата?",
                            QuizCategoryId = 3
                        },
                        new
                        {
                            Id = 162,
                            Answer = "ПАИСИЙ",
                            Question = "Кой български възрожденец през 1762 година е написал \"История славянобългарска\" ?",
                            QuizCategoryId = 3
                        },
                        new
                        {
                            Id = 163,
                            Answer = "БУДИТЕЛ",
                            Question = "Как се нарича човек, който води сънародниците си по пътя към духовен напредък?",
                            QuizCategoryId = 3
                        },
                        new
                        {
                            Id = 164,
                            Answer = "ПЕТЪР БЕРОН",
                            Question = "Името на народен будител, написал през 1824 година първия български учебник, известен като \"Рибен буквар\"",
                            QuizCategoryId = 3
                        },
                        new
                        {
                            Id = 165,
                            Answer = "ГАБРОВО",
                            Question = "В кой град през 1835 година било открито първото светско училище в България?",
                            QuizCategoryId = 3
                        },
                        new
                        {
                            Id = 166,
                            Answer = "ШИПКА",
                            Question = "На кой връх в Стара планина през август 1877 година българските опълченци проявили изключителен героизъм и успели да спрат турската армия?",
                            QuizCategoryId = 3
                        },
                        new
                        {
                            Id = 167,
                            Answer = "НИКОЛА ФИЧЕВ",
                            Question = "Името на известен български майстор през Възраждането, построил покрития мост в Ловеч, къщата с \"маймунката\" във Велико Търново и много други строежи",
                            QuizCategoryId = 3
                        });
                });

            modelBuilder.Entity("EducationalGame.Model.Principal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("SchoolName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.ToTable("Principals");
                });

            modelBuilder.Entity("EducationalGame.Model.QuizCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("QuizCategoryName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("QuizCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            QuizCategoryName = "Човекът и заобикалящия го свят"
                        },
                        new
                        {
                            Id = 2,
                            QuizCategoryName = "Нашата красива България"
                        },
                        new
                        {
                            Id = 3,
                            QuizCategoryName = "България в Средновековна Европа"
                        });
                });

            modelBuilder.Entity("EducationalGame.Model.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<long>("Coins");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("SchoolName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int?>("TeacherId");

                    b.Property<long>("TotalPoints");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("EducationalGame.Model.StudentGameQuiz", b =>
                {
                    b.Property<int>("StudentId");

                    b.Property<int>("GameQuizId");

                    b.HasKey("StudentId", "GameQuizId");

                    b.HasIndex("GameQuizId");

                    b.ToTable("StudentGameQuizes");
                });

            modelBuilder.Entity("EducationalGame.Model.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<int?>("PrincipalId");

                    b.Property<string>("SchoolName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.HasIndex("PrincipalId");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("EducationalGame.Model.GameQuiz", b =>
                {
                    b.HasOne("EducationalGame.Model.QuizCategory", "QuizCategory")
                        .WithMany("GameQuizes")
                        .HasForeignKey("QuizCategoryId");
                });

            modelBuilder.Entity("EducationalGame.Model.Student", b =>
                {
                    b.HasOne("EducationalGame.Model.Teacher", "Teacher")
                        .WithMany("Students")
                        .HasForeignKey("TeacherId");
                });

            modelBuilder.Entity("EducationalGame.Model.StudentGameQuiz", b =>
                {
                    b.HasOne("EducationalGame.Model.GameQuiz", "GameQuiz")
                        .WithMany("StudentGameQuizes")
                        .HasForeignKey("GameQuizId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EducationalGame.Model.Student", "Student")
                        .WithMany("StudentGameQuizes")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EducationalGame.Model.Teacher", b =>
                {
                    b.HasOne("EducationalGame.Model.Principal", "Principal")
                        .WithMany("Teachers")
                        .HasForeignKey("PrincipalId");
                });
#pragma warning restore 612, 618
        }
    }
}
